services:
    db:
        container_name: psaggregator_db
        restart: unless-stopped
        image: mysql:8.0
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        expose:
            - "3306"
        ports:
            - "127.0.0.1:3306:3306"

    youtube-api:
        image: ceramicwhite/youtube-operational-api
        container_name: youtube-api
        restart: unless-stopped
        ports:
            - "127.0.0.1:8080:80"
        expose:
            - "8080:80"
volumes:
    mysql:
