services:
    db:
        container_name: psaggregator_db
        restart: unless-stopped
        image: mysql:8.0
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        expose:
            - "3306"
        networks:
            - mysql

    frontend:
        container_name: psaggregator_frontend
        restart: unless-stopped
        image: ghcr.io/zaanposni/psaggregator_frontend:latest
        environment:
            - PRIVATE_DATABASE_URL=${DATABASE_URL}
            - PUBLIC_LEGAL_URL=${LEGAL_URL}
            - PUBLIC_MICROANALYTICS_ID=${MICROANALYTICS_ID}
            - PUBLIC_KOFI_USERNAME=${KOFI_USERNAME}
        depends_on:
            - db
        networks:
            - mysql
            - nginx
        expose:
            - "3000"

    dataimport:
        container_name: psaggregator_dataimport
        restart: unless-stopped
        image: ghcr.io/zaanposni/psaggregator_dataimport:latest
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
            - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
            - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
            - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - SQLALCHEMY_SILENCE_UBER_WARNING=1
            - YT_SERVER_BASE_URL=http://youtube-api
            - INSTAGRAM_USERNAME=${INSTAGRAM_USERNAME}
            - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD}
            - INSTAGRAM_2FA_SECRET=${INSTAGRAM_2FA_SECRET}
            - INSTAGRAM_CONFIG_PATH=/app/config/instagram.json
            - TWITTER_USERNAME=${TWITTER_USERNAME}
            - TWITTER_PASSWORD=${TWITTER_PASSWORD}
            - TWITTER_LIST_ID=${TWITTER_LIST_ID}
            - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
        volumes:
            - shared-data:/app/cdn
            - config:/app/config
        depends_on:
            - db
            - frontend
            - youtube-api
        networks:
            - mysql
            - youtube

    nginx:
        container_name: psaggregator_nginx
        restart: unless-stopped
        image: ghcr.io/zaanposni/psaggregator_nginx:latest
        volumes:
            - shared-data:/app/cdn
        depends_on:
            - frontend
        ports:
            - "127.0.0.1:5650:80"
        networks:
            - nginx

    youtube-api:
        image: benjaminloison/youtube-operational-api
        container_name: youtube-api
        restart: unless-stopped
        expose:
            - "80"
        networks:
            - youtube

networks:
    mysql:
    nginx:
    youtube:

volumes:
    mysql:
    config:
    shared-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./cdn
