name: Docker

on:
    pull_request:

jobs:
    build_frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build frontend
              working-directory: ./src/psaggregator
              run: docker build .

    build_nginx:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build nginx
              working-directory: ./src/nginx
              run: docker build .

    build_dataimport:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build dataimport
              working-directory: ./src/dataimport
              run: docker build .

    build_imageresizer:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build dataimport
              working-directory: ./src/imageresizer
              run: docker build .
