name: Python

on:
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Install dependencies
              working-directory: ./src/dataimport
              run: |
                  python -m pip install --upgrade pip
                  pip install pylint
                  pip install -r requirements.txt

            - name: Lint Python code
              working-directory: ./src/dataimport
              run: |
                  pylint --errors-only ./*.py
